name: ngdart_md_admin
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <you@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_forms: any
  angular_router: any
  angular_components: any

dev_dependencies:
  build_runner: ^1.6.1
  build_web_compilers: ^2.1.0
  sass_builder: ^2.1.2
  angular_test: ^2.2.0
  build_test: ^0.10.3
  pedantic: ^1.0.0
  test: ^1.6.4
